In [6]:
import os
from dotenv import load_dotenv
import tabpfn_client

load_dotenv()
tabpfn_client.set_access_token(os.getenv("API_TOKEN_PRIOR_LABS"))

In [1]:
from uci_gas_sensor_dataset import UCIGasSensorDataset

dataset = UCIGasSensorDataset()
dataset.load()

In [4]:
from evaluation import get_splits, run

from sklearn.pipeline import make_pipeline
import xgboost as xgb

xgb_model = make_pipeline(xgb.XGBClassifier())
splits = get_splits("batch1", dataset.df["batch"])
run(dataset.df[dataset.feature_columns].values, dataset.df["gas"].values, xgb_model, splits)

   test       acc   bal_acc
0     2  0.803055  0.675794
1     3  0.679697  0.564674
2     4  0.695652  0.507364
3     5  0.355330  0.406349
4     6  0.478261  0.420103
5     7  0.403820  0.425853
6     8  0.278912  0.423611
7     9  0.268085  0.300909
8    10  0.350278  0.350278

In [ ]:
from evaluation import get_splits, run

from sklearn.pipeline import make_pipeline
from tabpfn_client import TabPFNClassifier

tabpfn_model = make_pipeline(TabPFNClassifier())
splits = get_splits("batch1", dataset.df["batch"])
run(dataset.df[dataset.feature_columns].values, dataset.df["gas"].values, tabpfn_model, splits)

   test       acc   bal_acc
0     2  0.895498  0.814950
1     3  0.744641  0.652887
2     4  0.583851  0.589583
3     5  0.639594  0.580159
4     6  0.683913  0.468910
5     7  0.602270  0.608848
6     8  0.241497  0.344286
7     9  0.512766  0.550738
8    10  0.502500  0.502500