In [1]:
from uci_gas_sensor_dataset import UCIGasSensorDataset

dataset = UCIGasSensorDataset()
dataset.load()

FileNotFoundError: [Errno 2] No such file or directory: 'data/batch1.dat'

In [5]:
from evaluation import get_splits, run

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

logreg_model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=5000))
splits = get_splits("batch1", dataset.df["batch"])
run(dataset.df[dataset.feature_columns].values, dataset.df["gas_name"].values, logreg_model, splits)

   test       acc   bal_acc
0     2  0.831190  0.767859
1     3  0.634931  0.516850
2     4  0.540373  0.363057
3     5  0.350254  0.415000
4     6  0.466957  0.330019
5     7  0.437586  0.458545
6     8  0.323129  0.482365
7     9  0.342553  0.333333
8    10  0.375833  0.375833

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = make_pipeline(StandardScaler(), KNeighborsClassifier(5))
splits = get_splits("batch1", dataset.df["batch"])
run(dataset.df[dataset.feature_columns].values, dataset.df["gas_name"].values, knn_model, splits)

   test       acc   bal_acc
0     2  0.678457  0.578008
1     3  0.414250  0.305245
2     4  0.316770  0.354312
3     5  0.253807  0.276667
4     6  0.340000  0.310867
5     7  0.327706  0.363246
6     8  0.163265  0.238426
7     9  0.359574  0.357576
8    10  0.450556  0.450556